apps/frontend/src/app/[locale]/[...not-found]/page.tsx, apps/frontend/src/app/[locale]/demo/page.tsx, apps/frontend/src/app/[locale]/not-found.tsx, apps/frontend/src/app/[locale]/page.tsx, apps/frontend/src/app/[locale]/products/[slug]/page.tsx, apps/frontend/src/app/[locale]/products/alphabet/[q]/page.tsx, apps/frontend/src/app/[locale]/products/page.tsx, apps/frontend/src/app/[locale]/samenwerkendecatalogi.xml/route.ts, apps/frontend/src/app/[locale]/search/tips/[query]/page.tsx, apps/frontend/src/app/[locale]/sitemap.xml/route.tsx, apps/frontend/src/app/api/current-pathname/route.ts, apps/frontend/src/app/api/preview/route.ts, apps/strapi-dashboard/src/components/components/vng-attributes.json
This reverts commit 78a1e3d7ca34e05ebc72858589cbedf422d1c60f.
=> Revert "chore: update the backend-url"

apps/strapi-dashboard/src/api/product/content-types/product/schema.json, apps/strapi-dashboard/src/components/components/accordion-section.json, apps/strapi-dashboard/src/components/components/block-content.json, apps/strapi-dashboard/src/components/components/button-link.json, apps/strapi-dashboard/src/components/components/faq.json, apps/strapi-dashboard/src/components/components/image.json, apps/strapi-dashboard/src/components/components/logo-button.json, apps/strapi-dashboard/src/components/components/multi-columns-button.json, apps/strapi-dashboard/src/components/components/price.json, apps/strapi-dashboard/src/components/components/spotlight.json
=> fix: make `displayName` prettier for the section components

apps/pdc-frontend/src/app/[locale]/products/[slug]/page.tsx
https://developer.pandosearch.com/guides/keymatch/
=> fix: replace replace keywords with keymatch

apps/pdc-frontend/src/app/i18n/locales/en/common.json, apps/pdc-frontend/src/app/i18n/locales/nl/common.json, apps/pdc-frontend/src/components/Markdown/index.tsx, packages/strapi-tiptap-editor/admin/src/components/Editor/PriceList.tsx, packages/strapi-tiptap-editor/admin/src/components/Editor/Toolbar.tsx, packages/strapi-tiptap-editor/admin/src/components/extensions/Price/widget.tsx, packages/strapi-tiptap-editor/admin/src/translations/en.json, packages/strapi-tiptap-editor/admin/src/translations/nl.json, packages/strapi-tiptap-editor/admin/src/utils/getPriceValue.ts, packages/strapi-tiptap-editor/admin/src/utils/index.ts
=> Enable to display free | gratis when the price is zero

apps/pdc-dashboard/src/components/components/e-form.json, apps/pdc-dashboard/src/components/components/identification-method.json, apps/pdc-dashboard/src/components/components/metadata.json, apps/pdc-dashboard/src/components/components/url.json
=> feat(pdc-dashboard): update metadata

apps/pdc-dashboard/package.json, yarn.lock
it's to visualize content types and their relationships
=> feat(pdc-dashboard): add strapi-content-type-explorer

.prettierrc.json, apps/pdc-frontend/src/app/[locale]/layout.tsx, apps/pdc-frontend/src/app/[locale]/page.tsx, apps/pdc-frontend/src/components/Toptask/index.module.scss, apps/pdc-frontend/src/components/Toptask/index.tsx, apps/pdc-frontend/src/styles/globals.css, packages/ui/src/components/Grid/index.module.scss, packages/ui/src/components/Grid/index.tsx, packages/ui/src/components/index.tsx
- Open the terminal and navigate to the directory `cd apps/pdc-frontend`.
- Start the local server by executing the following command: `yarn dev`.
- Once the server is running, open your web browser and go to [http://localhost:3000/grid](http://localhost:3000/grid).
- You can find the grid demo page under `/apps/pdc-frontend/app/[locale]/grid`
=> Create grid component

apps/pdc-frontend/src/styles/globals.css
this is a temporary solution until this [PR](https://github.com/nl-design-system/utrecht/pull/1968) get merged
=> fix(pdc-frontend): fix the spacing for the accordion item

apps/pdc-dashboard/package.json, apps/vth-dashboard/package.json, yarn.lock
the previous version was broken
https://github.com/boazpoolman/strapi-plugin-config-sync/issues/110
=> fix(deps): upgrade strapi-plugin-config-sync to v1.2.2

packages/strapi-tiptap-editor/admin/src/components/Editor/Toolbar.tsx, packages/strapi-tiptap-editor/admin/src/components/LinkDialog/index.tsx, packages/strapi-tiptap-editor/admin/src/hooks/useLink.ts, packages/strapi-tiptap-editor/admin/src/translations/en.json, packages/strapi-tiptap-editor/admin/src/translations/nl.json, packages/strapi-tiptap-editor/utils/helpers.ts
=> feat(strapi-tiptap): add validation to the lint

.yarnrc, README.md, package.json, packages/strapi-tiptap-editor/admin/src/components/Editor/TableMenuBar.tsx, packages/strapi-tiptap-editor/admin/src/components/Wysiwyg/index.tsx
=> style: enable dark mode for Strapi admin

apps/pdc-dashboard/config/sync/admin-role.strapi-super-admin.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.cim-pdc-product-aspect-beschrijving.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.cim-pdc-product-beschrijving.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.cim-pdc-product-metadata.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_content_types##api##productencatalogus.productencatalogus.json, apps/pdc-dashboard/src/api/product/content-types/product/schema.json, apps/pdc-dashboard/src/api/productencatalogus/content-types/productencatalogus/schema.json, apps/pdc-dashboard/src/api/productencatalogus/controllers/productencatalogus.ts, apps/pdc-dashboard/src/api/productencatalogus/routes/productencatalogus.ts, apps/pdc-dashboard/src/api/productencatalogus/services/productencatalogus.ts, apps/pdc-dashboard/src/components/components/cim-pdc-product-aspect-beschrijving.json, apps/pdc-dashboard/src/components/components/cim-pdc-product-beschrijving.json, apps/pdc-dashboard/src/components/components/cim-pdc-product-metadata.json
=> feat: add cimpdc productencatalogus and product metadata

apps/pdc-frontend/src/app/[locale]/form/[slug]/page.tsx, apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsEmbed.tsx, apps/pdc-frontend/src/middleware.ts
This PR contains the initial setup for CSP in NextJS based on [this documentation](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy).
=> feat: add csp configuration

apps/pdc-frontend/src/components/Markdown/index.tsx, apps/pdc-frontend/src/components/index.tsx, packages/ui/src/components/AdvancedLink/index.tsx, packages/ui/src/components/LogoButton/index.tsx, packages/ui/src/components/Markdown/index.tsx, packages/ui/src/components/MultiColumnsLogoButton/index.tsx, packages/ui/src/components/Navigation/NavigationLink/index.tsx
=> chore: move component imports away from css-module

.ncurc.major.js, .ncurc.minor.js, .ncurc.patch.js, package.json, yarn.lock
npm-check-updates has been installed
The scripts are running
*Currently working on a patch update in a different branch
[npmjs npm-check-updates page](https://www.npmjs.com/package/npm-check-updates#config-file)
=> chore: installed npm-check-updates

packages/ui/src/components/Footer/index.tsx
add aria label to footer for accessibility
=> add aria label to footer

apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/[slug]/page.tsx, packages/ui/src/components/MultiColumnsLogoButton/index.tsx
https://github.com/orgs/frameless/projects/27/views/7?pane=issue&itemId=55845479
=> Fix logo button

apps/pdc-frontend/gql/graphql.ts
It appears that we forgat to update the codegen output in this [PR](https://github.com/frameless/strapi/pull/518)
=> chore(pdc): update codegen output

apps/pdc-frontend/src/middleware.ts
add youtube frame src so youtube iframes work
=> feat: youtube added to csp

apps/pdc-frontend/src/app/[locale]/sitemap.xml/route.tsx
=> chore(pdc-frontend): fix the sitemap.xml

apps/pdc-frontend/src/styles/openforms.scss
moet nog gerebased worden op https://github.com/frameless/strapi/pull/658 of main als die pull request in gemerged
=> style: vorige knop links uitgelijned

apps/pdc-frontend/src/app/[locale]/(rootLayout)/search/[query]/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/search/tips/[query]/page.tsx
=> chore(pdc-frontend): fix the search page title

apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/error.tsx, apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/form/[...slug]/page.tsx, apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/form/error/[errorKey]/page.tsx, apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/layout.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/[...not-found]/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/error.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/layout.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/not-found.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/[slug]/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/alphabet/[q]/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/search/[query]/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/search/tips/[query]/page.tsx, apps/pdc-frontend/src/app/i18n/locales/en/common.json, apps/pdc-frontend/src/app/i18n/locales/en/layout.json, apps/pdc-frontend/src/app/i18n/locales/nl/common.json, apps/pdc-frontend/src/app/i18n/locales/nl/layout.json, packages/ui/src/components/Breadcrumb/index.tsx, packages/ui/src/components/Navigation/NavigationList/index.tsx, packages/ui/src/components/Navigation/index.tsx
Voor issue #682
https://github.com/frameless/strapi/assets/53454241/c93f4f4c-1d80-4add-914b-e19e3ccc94af
=> Fix inconsistent behavior of skip links

apps/pdc-dashboard/src/admin/app.ts, apps/vth-dashboard/src/admin/app.ts
[Issue link](https://github.com/frameless/strapi/issues/704)
=> chore(pdc-dashboard): disable Promoter Score popup

apps/vth-frontend/src/app/[locale]/sitemap.ts, apps/vth-frontend/src/query/index.ts
[Issue Link](https://github.com/orgs/frameless/projects/14/views/7?pane=issue&itemId=63898787)
=> chore(vth-frontend): add sitemap

packages/strapi-tiptap-editor/admin/src/components/TableWidget/index.tsx, packages/strapi-tiptap-editor/admin/src/components/TableWidget/styles.css, packages/strapi-tiptap-editor/admin/src/components/Wysiwyg/index.tsx, packages/strapi-tiptap-editor/admin/src/components/extensions/CustomTable/index.tsx, packages/strapi-tiptap-editor/admin/src/components/extensions/Figure/index.tsx, packages/strapi-tiptap-editor/admin/src/utils/cursorPositionHandler.ts, packages/strapi-tiptap-editor/admin/src/utils/findClosestTable.ts, packages/strapi-tiptap-editor/admin/src/utils/index.ts
[Issue Link](https://github.com/orgs/frameless/projects/14/views/7?pane=issue&itemId=63893255)
https://github.com/frameless/strapi/assets/53454241/60cb4837-5aff-4291-b420-7794c7bc69e1
=> feat(strapi-tiptap-editor): improve table cursor positioning

.github/workflows/release.yml, .github/workflows/wcag.yaml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#discussion
```yaml
- labelled => labeled
- unlabelled => unlabeled
```
=> Use fixed version of GitHub action

apps/vth-frontend/src/app/[locale]/(rootLayout)/print/page.tsx
This issue causes build failure.
=> chore(vth-frontend): fix style import

.eslintrc.js, apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/layout.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/layout.tsx, apps/pdc-frontend/src/app/i18n/locales/en/layout.json, apps/pdc-frontend/src/app/i18n/locales/nl/layout.json, apps/vth-frontend/src/app/[locale]/(nestedNavLayout)/layout.tsx, apps/vth-frontend/src/app/[locale]/(rootLayout)/layout.tsx, apps/vth-frontend/src/app/i18n/locales/nl/layout.json, packages/ui/jest.config.ts, packages/ui/package.json, packages/ui/src/components/Footer/index.module.scss, packages/ui/src/components/Footer/index.tsx, packages/ui/src/components/HTMLHeading/HTMLHeading.test.tsx, packages/ui/src/components/HTMLHeading/index.tsx, packages/ui/src/components/Nav/Nav.test.tsx, packages/ui/src/components/Nav/index.tsx, packages/ui/src/components/index.tsx, packages/ui/tsconfig.test.json
[issue link](https://github.com/orgs/frameless/projects/27/views/7?filterQuery=&pane=issue&itemId=61471643)
=> Fix the social media accessibility issue

packages/ui/src/components/Footer/index.tsx
=> fix: avoid rendering an empty link list

apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/form/[...slug]/page.tsx, apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/layout.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/layout.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/[slug]/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/alphabet/[q]/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/search/[query]/page.tsx, apps/pdc-frontend/src/styles/globals.css
All text should be inside a landmark.
=> fix: include links inside main landmark

.changeset/thin-islands-sell.md, apps/kennisbank-frontend/package.json, apps/pdc-frontend/package.json, apps/pdc-frontend/src/app/[locale]/(rootLayout)/layout.tsx, apps/pdc-frontend/src/components/GoogleTranslate/index.tsx, apps/pdc-frontend/src/components/index.tsx, apps/vth-frontend/package.json, packages/ui/package.json, packages/ui/src/components/GoogleTranslate/index.tsx, packages/ui/src/components/index.tsx, packages/ui/src/util/google-translate-adapation.test.tsx, packages/ui/src/util/google-translate-adaptation.ts, packages/ui/src/util/google-translate-event.test.tsx, packages/ui/src/util/google-translate-event.ts, yarn.lock
=> feat: adapt text-direction to Google Translate locale

packages/ui/src/components/Footer/index.tsx, packages/ui/src/components/Navigation/NavigationList/index.tsx, packages/ui/src/components/Navigation/NavigationMarker/index.tsx, packages/ui/src/components/ProductList/index.tsx
The console in Node.js was littered with warnings, this fixes most of them.
=> fix: various React warnings

.changeset/hot-keys-lick.md, .changeset/nasty-buses-check.md, .changeset/new-cherries-jog.md, .eslintrc.js, .eslintrc.react.json, .github/workflows/release.yml, .gitignore, .stylelintignore, apps/pdc-frontend/jest.config.ts, apps/pdc-frontend/package.json, apps/pdc-frontend/playwright.config.ts, apps/pdc-frontend/src/middleware.ts, apps/pdc-frontend/test/e2e/example.spec.ts, packages/ui/package.json, yarn.lock
Great VSCode extension to have for Playwright:
https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright
=> test: add Playwright end-to-end tests

.changeset/cold-points-approve.md, packages/strapi-tiptap-editor/admin/src/components/Editor/editor.scss, packages/strapi-tiptap-editor/admin/src/components/Editor/index.tsx, packages/strapi-tiptap-editor/admin/src/components/Editor/styles.ts, packages/strapi-tiptap-editor/admin/src/components/Wysiwyg/RichTextEditorCanvas.scss, packages/strapi-tiptap-editor/admin/src/components/Wysiwyg/index.tsx, packages/strapi-tiptap-editor/admin/src/utils/getLocalStorage.ts, packages/strapi-tiptap-editor/admin/src/utils/index.ts
[issue](https://github.com/frameless/strapi/issues/866)
https://github.com/user-attachments/assets/af99353c-a058-49af-8d33-dce66536a7c3
=> fix(strapi-tiptap-editor): fix strapi rich-text field dark mode issue

apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/[slug]/page.tsx, packages/ui/src/components/Markdown/index.tsx
voegd rich text toe aan de pdc die om de alle content staat
=> Pdc richtext component

apps/overige-objecten-api/src/__mocks__/getStrapiKennisartikelData.ts, apps/overige-objecten-api/src/__mocks__/getStrapiVacData.ts, apps/overige-objecten-api/src/controllers/objects/index.test.ts, apps/overige-objecten-api/src/controllers/objects/index.ts, apps/overige-objecten-api/src/controllers/openapi/index.test.ts, apps/overige-objecten-api/src/controllers/openapi/index.ts, apps/overige-objecten-api/src/docs/openapi.yaml, apps/overige-objecten-api/src/queries/index.ts, apps/overige-objecten-api/src/strapi-product-type.ts, apps/overige-objecten-api/src/utils/getPaginatedResponse.ts, apps/overige-objecten-api/src/utils/index.ts
use regex to validate the url instead of depend on value
=> fix: fix the type parameter issue

apps/pdc-dashboard/src/components/components/internal-block-content.json
the issue was because of the collectionName length https://github.com/strapi/strapi/issues/3409
=> fix: internal-field issue

.changeset/chatty-buckets-tickle.md, packages/strapi-tiptap-editor/admin/src/components/Wysiwyg/index.tsx, packages/strapi-tiptap-editor/admin/src/context/productPrice/context.ts, packages/strapi-tiptap-editor/admin/src/context/productPrice/state.tsx
https://github.com/frameless/strapi/issues/983
=> feat: integrate the price widget into internal field

.changeset/pretty-plants-retire.md, apps/pdc-frontend/package.json, apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsEmbed.scss, yarn.lock
[issue](https://github.com/frameless/strapi/issues/959)
=> fix: fix table style in open forms embed

.changeset/six-islands-laugh.md, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.antwoord.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.internal-block-content.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.internal-field.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.vac.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_content_types##api##internal-field.internal-field.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_content_types##api##vac.vac.json, apps/pdc-dashboard/src/admin/app.ts, apps/pdc-dashboard/src/components/components/internal-block-content.json
[issue](https://github.com/frameless/strapi/issues/990)
=> feat: improve vac and internal field labels

.changeset/cyan-buttons-flash.md, apps/pdc-dashboard/config/sync/admin-role.pdc-lezer-m5uuxokf.json, apps/pdc-dashboard/config/sync/admin-role.pdc-schrijver-m5uxb98h.json
**This update is based on the Refinement meeting with Utrecht**
- pdc-schrijver: can read and write home-page content
- pdc-lezer: can read home-page content
=> feat: update pdc writer and reader roles

.changeset/honest-chefs-battle.md, .changeset/selfish-paws-join.md, apps/pdc-dashboard/config/plugins.ts, packages/preview-button/README.md, packages/preview-button/admin/src/components/DialogPreviewButton/index.jsx, packages/preview-button/admin/src/components/PreviewLink/index.css, packages/preview-button/admin/src/components/PreviewLink/index.js, packages/preview-button/admin/src/translations/en.json, packages/preview-button/admin/src/translations/nl.json, packages/preview-button/admin/src/utils/addHeadingOncePerCategory.js, packages/preview-button/admin/src/utils/combineSimilarCategories.js, packages/preview-button/admin/src/utils/getContentByType.js, packages/preview-button/admin/src/utils/getPreviewUrl.js, packages/preview-button/admin/src/utils/index.js, packages/preview-button/admin/src/utils/processProductData.jsx
[issue](https://github.com/frameless/strapi/issues/1022)
=> feat(preview-button): add additional information to the preview button

.changeset/heavy-points-repair.md, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_content_types##api##additional-information.additional-information.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_content_types##api##pdc-subcategory.pdc-subcategory.json, apps/pdc-dashboard/src/api/internal-field/content-types/internal-field/schema.json, apps/pdc-dashboard/src/api/vac/content-types/vac/schema.json
[issue](https://github.com/frameless/strapi/issues/1055)
=> fix(pdc-dashboard): improve the Strapi-dashboard labels

.changeset/proud-monkeys-fry.md, packages/preview-button/admin/src/components/PreviewLink/index.js, packages/preview-button/admin/src/translations/en.json, packages/preview-button/admin/src/translations/nl.json, packages/preview-button/admin/src/utils/concatenateFieldValues.js, packages/preview-button/admin/src/utils/getUIDFromHref.js, packages/preview-button/admin/src/utils/index.js
[issue](https://github.com/frameless/strapi/issues/1057)
=>  preview internal field data within the product collection.

.changeset/beige-owls-sit.md, .changeset/hot-shrimps-burn.md, apps/overige-objecten-api/src/controllers/objects/index.test.ts, apps/overige-objecten-api/src/queries/index.ts, apps/overige-objecten-api/src/strapi-product-type.ts, apps/overige-objecten-api/src/utils/generateKennisartikelObject.ts, apps/overige-objecten-api/src/utils/generateKeywords.ts, apps/overige-objecten-api/src/utils/index.ts, apps/pdc-dashboard/config/sync/admin-role.beheerder-m5uxzjc8.json, apps/pdc-dashboard/config/sync/admin-role.kennisbank-lezer-m5uvxm3k.json, apps/pdc-dashboard/config/sync/admin-role.kennisbank-schrijver-m5uxgzkp.json, apps/pdc-dashboard/config/sync/admin-role.strapi-super-admin.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.internal-field.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.trefwoorden.json, apps/pdc-dashboard/src/components/components/internal-field.json
[issue](https://github.com/frameless/strapi/issues/1047)
=> Add trefwoorden to internal field

.dockerignore, .yarnrc, Dockerfile.prod, docker-compose.vth.prod.yml, package.json
- Added comments to explain each step for better maintainability
- Ensured `set -eux` is used to catch errors early in critical steps
- Improved dependency installation with explicit package management
- Switched to a multi-stage build to keep the final image lightweight
**yarnrc**:
- Disable Yarn self-update check to speed up installs and avoid noise
- FIX `frozen-lockfile` syntax to ensure dependency consistency
=> chore(docker): improve Dockerfile for better efficiency and reliability

.changeset/funny-moles-report.md, .changeset/gold-mirrors-explode.md, apps/overige-objecten-api/src/controllers/objects/index.test.ts, apps/overige-objecten-api/src/controllers/objects/index.ts, apps/overige-objecten-api/src/queries/index.ts, apps/overige-objecten-api/src/strapi-product-type.ts, packages/preview-button/admin/src/components/PreviewLink/index.js
[issue](https://github.com/frameless/strapi/issues/1062)
=> feat(overige-objecten-api): return first contentBlock as inleiding category when provided

.changeset/big-lemons-act.md, .changeset/violet-needles-doubt.md, apps/overige-objecten-api/src/utils/addHeadingOncePerCategory.test.ts, apps/overige-objecten-api/src/utils/addHeadingOncePerCategory.ts, packages/preview-button/admin/src/utils/addHeadingOncePerCategory.js
[issue](https://github.com/frameless/strapi/issues/1070)
=> Add hr to additional info field

.changeset/rich-oranges-add.md, packages/preview-button/package.json, yarn.lock
[issue](https://github.com/frameless/strapi/issues/1071)
=> fix(preview-button): fix ordered-list style issue

.changeset/bright-countries-pretend.md, apps/pdc-frontend/src/components/ProductListContainer/index.tsx, packages/ui/src/components/ProductList/index.module.scss, packages/ui/src/components/ProductList/index.tsx
[Issue](https://github.com/frameless/strapi/issues/1128)
**Before**:
https://github.com/user-attachments/assets/688decfa-0da5-4557-b3fd-0d7b9fff688b
**After**:
https://github.com/user-attachments/assets/136140d1-9b87-4768-8147-31cac8b65fd4
=> fix(ui): prevent scroll jump on focus for pagination info element

.changeset/famous-hairs-warn.md, .changeset/yellow-fireants-behave.md, apps/pdc-frontend/src/app/[locale]/(rootLayout)/products/page.tsx, apps/pdc-frontend/src/app/[locale]/(rootLayout)/search/[query]/page.tsx, apps/pdc-frontend/src/app/i18n/locales/en/product-list-container-component.json, apps/pdc-frontend/src/app/i18n/locales/en/search-page.json, apps/pdc-frontend/src/app/i18n/locales/nl/product-list-container-component.json, apps/pdc-frontend/src/app/i18n/locales/nl/search-page.json, apps/pdc-frontend/src/components/ProductListContainer/index.tsx, packages/ui/src/components/ProductList/index.tsx
[Issue ](https://github.com/frameless/strapi/issues/1090)
https://github.com/user-attachments/assets/f08a80ad-be05-42c0-82d6-eea786a412b8
=> fix(pdc-frontend): display the pagination information initially

.changeset/tall-hornets-enjoy.md, packages/ui/src/components/Navigation/NavigationList/index.test.tsx, packages/ui/src/components/Navigation/NavigationList/index.tsx
[Issue](https://github.com/frameless/strapi/issues/1030)
=> fix(ui): ensure that the focus behavior of the navigation links is explicitly prevented in mobile mode

.changeset/green-bikes-enjoy.md, packages/strapi-tiptap-editor/admin/src/components/Editor/Toolbar.tsx, packages/strapi-tiptap-editor/admin/src/components/Editor/index.tsx, packages/strapi-tiptap-editor/admin/src/components/Editor/styles.ts, packages/strapi-tiptap-editor/admin/src/components/Wysiwyg/RichTextEditorCanvas.scss, packages/strapi-tiptap-editor/package.json, packages/tiptap-editor/src/components/Editor/index.tsx, yarn.lock
https://github.com/frameless/strapi/issues/1135
https://github.com/user-attachments/assets/71a02b7a-08f9-4c80-a34c-dfc4fef2e9cc
=> fix: fix tiptap editor toolbar sticky issue

.changeset/thirty-pans-float.md, packages/preview-button/admin/src/components/PreviewLink/index.css, packages/preview-button/admin/src/components/PreviewLink/index.js, packages/utils/src/addHeadingOncePerCategory/index.test.ts, packages/utils/src/addHeadingOncePerCategory/index.ts
[Issue ](https://github.com/frameless/strapi/issues/1136)
https://github.com/user-attachments/assets/1deb0cf0-ae51-49ba-a33a-f1ed47d21c40
=> Improve additional information block in preview

.changeset/loud-forks-reply.md, apps/pdc-dashboard/config/sync/admin-role.beheerder-m5uxzjc8.json, apps/pdc-dashboard/config/sync/admin-role.kennisbank-schrijver-m5uxgzkp.json, apps/pdc-dashboard/config/sync/admin-role.pdc-lezer-m5uuxokf.json, apps/pdc-dashboard/config/sync/admin-role.pdc-schrijver-m5uxb98h.json, apps/pdc-dashboard/config/sync/admin-role.strapi-super-admin.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_content_types##api##contact-detail.contact-detail.json, apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_content_types##api##product.product.json, apps/pdc-dashboard/src/api/contact-detail/content-types/contact-detail/schema.json, apps/pdc-dashboard/src/api/contact-detail/controllers/contact-detail.ts, apps/pdc-dashboard/src/api/contact-detail/routes/contact-detail.ts, apps/pdc-dashboard/src/api/contact-detail/services/contact-detail.ts, apps/pdc-dashboard/src/api/product/content-types/product/schema.json, apps/pdc-dashboard/src/api/vac/content-types/vac/schema.json, apps/strapi.frameless.io/docs/handboek/rollen-en-mogelijkheden-in-strapi-dashboard.md
[issue](https://github.com/frameless/strapi/issues/1151)
=> feat(pdc-dashboard): Add new contact details collection

apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsEmbed.tsx, apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsNLDesignSystem.tsx, apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsScript.tsx, apps/pdc-frontend/src/components/OpenFormsEmbed/useOpenFormsWysiwygStyling.ts
=> fix(pdc-frontend): add MutationObserver to apply utrecht-html class to rich text elements

.changeset/three-lions-cough.md, apps/overige-objecten-api/src/components/AccordionSection.tsx, apps/overige-objecten-api/src/utils/processData.test.ts
This reverts commit d19d7e98fa06b04b7567f742a802808f3d3c0f60.
=> Reapply "feat(overige-objecten-api): implement collapsible sections"
