apps/frontend/src/styles/globals.css

this is a temperately until we add it from the utrecht theme package

fix: add spacing tokens value to spotlight component

---

apps/strapi-dashboard/src/api/price/content-types/price/schema.json
apps/strapi-dashboard/src/components/components/price.json

fix: set price field label to required to prevent `null` issue

---

apps/vth-dashboard/src/api/thema-content/content-types/thema-content/schema.json
apps/vth-dashboard/src/api/thema/content-types/thema/schema.json

Adds parent relation between `thema` and `thema-content`. This allows sub-themas and linking thema-contents directly to main themas.

feat: add parent relation to thema and thema-content

---

apps/pdc-frontend/package.json
apps/vth-frontend/package.json
yarn.lock

I believe that we mistakenly installed Yarn as a dependency in our Next.js applications.

chore: remove yarn from nextjs apps dependencies

---

apps/vth-dashboard/src/api/homepage/content-types/homepage/schema.json
apps/vth-dashboard/src/api/thema-content/content-types/thema-content/schema.json
apps/vth-dashboard/src/api/thema/content-types/thema/schema.json
apps/vth-frontend/src/app/[locale]/page.tsx
apps/vth-frontend/src/components/Card/index.style.css
apps/vth-frontend/src/components/Logo/index.tsx
apps/vth-frontend/src/query/index.ts
apps/vth-frontend/src/styles/globals.css

- Banner image on homepage
- Red accent above banner image as separation
- Banner image upload in strapi for the homepage type
- Disallow all media types except images for previously added preview images on card
- Card image sizing
- Card description not showing on thema pages
- (temporary fix): Float menu button into header
- (temporary fix): Add `padding-block-end` to header
- (temporary fix): Add `border-block-end` to navigation

feat(vth): add banner image

---

apps/pdc-frontend/global.d.ts
apps/pdc-frontend/src/components/SearchBar/index.tsx

This is a temporary solution until we discover the root cause of the issue. Normally, we obtain react types from Next.js under the experimental when we use server action. However, currently, we obtain them from Canary.

fix(pdc-frontend): fix the `useOptimistic` issue

---

apps/vth-frontend/src/components/Card/index.style.css

Removes a text decoration overwrite to make sure all card links retain their underline. Adds a few card hover styles to ensure the underline is identical when hovering over the card and hovering over the link specifically.

fix(vth): card style with link underline

---

apps/vth-frontend/src/app/[locale]/layout.tsx
packages/ui/src/components/Navigation/NavigationItem/index.module.scss
packages/ui/src/components/Navigation/NavigationList/index.module.scss
packages/ui/src/components/Navigation/NavigationList/index.tsx
packages/ui/src/components/Navigation/index.module.scss
packages/ui/src/components/Navigation/index.tsx

Adds support for navigation sub links in the mobile view. This is required by the VTH project, and creates a starting point for us to fully support sub navigational links in non-mobile views as well should we wish to have them. Also exported the navigation item type for easier use by consuming projects.

feat(ui): support sub links in navigation

---

packages/strapi-tiptap-editor/admin/src/components/Editor/TableMenuBar.tsx
packages/strapi-tiptap-editor/admin/src/components/Editor/styles.ts

Issue Description:
- When you highlight text inside the table, the menubar popup appears.
- If you choose an option to modify the table, for example, ROW => insert row below, it works the first time but doesn't work when you try to add more rows.

fix(strapi-tiptap-editor): resolve table Menubar option issue

---

apps/pdc-frontend/package.json
apps/pdc-frontend/src/components/Markdown/index.tsx
apps/vth-frontend/package.json
yarn.lock

[chore:(deps): remove unused dependencies](https://github.com/frameless/strapi/pull/321/commits/28b7103705d25800fdc26d12633cb2db28179d1b) 
**pdc-frontend:**
- `add`: This appears to have been added accidentally.
**vth-frontend:**
- `add`: This appears to have been added accidentally.
- `downshift`: Not in use.
- `react-markdown, rehype-raw`: No longer needed in Next.js, as we import markdown from the @frameless/ui package.
[chore(pdc-frontend): import the correct types from react-markdown](https://github.com/frameless/strapi/pull/321/commits/b10eaa6dba24130a90b5d03dee5ccf06291eb4f1) 
These types became available after removing react-markdown from vth-frontend.

Remove unused dependency

---

.stylelintrc.json

Fixed stylelint warning:
> Deprecation warnings:
>  - The "scss/at-import-no-partial-leading-underscore" rule is deprecated.
>  - 'at-import-no-partial-leading-underscore' has been deprecated, and will be removed in '6.0'. Use 'load-no-partial-leading-underscore' instead. See: https://github.com/stylelint-scss/stylelint-scss/blob/v5.2.1/src/rules/at-import-no-partial-leading-underscore/README.md

chore(stylelint): fix deprecated rule

---

packages/ui/src/components/index.tsx

There's an error right now when building `main`, a type export got lost in a refactor.

fix: ui type export

---

apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/form/[...slug]/page.tsx

closes 
- #416 
Implements the [catch-all route segment feature](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#catch-all-segments) for the form route. Effectively this allows us to catch anything after `/form/..`, for example: `/form/form-id/form-step` and make sure we only pass the `form-id` route segment to the OpenFormsSDK. 
This leaves the SDK free to interpret which step to load from the remainder of the URL, which means we can refresh the form embed page without losing the form or step 🚀

feat: support form page refresh

---

apps/pdc-frontend/package.json
apps/pdc-frontend/src/middleware.ts
yarn.lock

> **Note**: According to the [OpenForms documentation](https://open-forms.readthedocs.io/en/stable/developers/csp.html?highlight=service.pdok.nl#embedding-using-the-sdk), it appears that they utilize [PDOK](https://www.pdok.nl/) for map support rather than Google Maps."

add google maps cps

---

packages/strapi-plugin-open-forms-embed/admin/src/components/CustomCombobox/index.tsx
packages/strapi-plugin-open-forms-embed/admin/src/hooks/use-plugin-config.ts

This issue occurs when using the same field twice for a product in Strapi. The issue arises when refreshing or revisiting the page.

fix(plugin-open-forms-embed): fix the infinity loop request issue

---

packages/ui/src/components/Navigation/index.tsx

The button already has descriptive text so `aria-label` is not needed

fix(ui): remove unneeded `aria-label` from `NavToggleButton`

---

packages/ui/src/hooks/useClickOutside.ts

The `preventDefault()` here overrides every click event and prevents selection of text. I couldn't find any reason to prevent default here. It seems we can safely remove this and keep the drawer clickOutside functionality working.

fix: click outside hook overriding default

---

apps/pdc-dashboard/src/components/components/cim-pdc-product-metadata.json
apps/pdc-frontend/gql/graphql.ts
apps/pdc-sc/src/server.ts
packages/samenwerkende-catalogi/src/index.ts

- Updates query to get UPL from pdc_metadata
- Sets some (Cim)PDC Metadata fields to optional 
- This needs to be done because the content editors are not familiar with all fields that are required in the CimPDC model. If we don't set those fields to optional, they won't be able to add a UPL. This is assuming that complete CimPDC metadata entry according to the model is less important (than the functionality of the the Samenwerkende Catalogi)
- Update codegen
- Update parsing code to use UPL field from metadata

fix: upl field in samenwerkende catalogi

---

packages/strapi-tiptap-editor/admin/src/components/Editor/Toolbar.tsx
packages/strapi-tiptap-editor/admin/src/components/extensions/LeadParagraph/index.ts

closes 
- #568 
It's hard to figure out the optimal way to implement this through Tip Tap docs. As long as the end result is a paragraph with the correct `data-lead` attribute, and it can store and load that, we should be safe if we wish to implement this differently in the future.

fix: lead paragraph not rendering correctly

---

apps/pdc-frontend/src/app/[locale]/sitemap.ts

The problem happened because the FRONTEND_PUBLIC_URL  environment variable wasn't there during the build on GitHub, and the new URL doesn't allow empty string.

chore(pdc-frontend): fix docker build on Github-Actions

---

packages/strapi-plugin-open-forms-embed/admin/src/components/CustomCombobox/index.tsx

Closes #579 
Uses a faster API endpoint that exposes less data. [Swagger reference](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/open-formulieren/open-forms/2.6.0/src/openapi.yaml#/).

feat: use new open forms public api

---

packages/ui/src/components/Markdown/index.tsx

Ensure that the ReactMarkdown component correctly renders links when the href attribute contains 'tel:'.
[Issue link](https://github.com/frameless/strapi/issues/735)

fix(ui): enable ReactMarkdown to render 'tel:' links

---

apps/pdc-frontend/src/app/[locale]/(rootLayout)/[...not-found]/page.tsx
apps/pdc-frontend/src/app/[locale]/(rootLayout)/not-found.tsx
apps/vth-frontend/src/app/[locale]/(nestedNavLayout)/not-found.tsx
apps/vth-frontend/src/app/[locale]/(rootLayout)/[...not-found]/page.tsx
apps/vth-frontend/src/app/[locale]/(rootLayout)/not-found.tsx

[Issue Link](https://github.com/frameless/strapi/issues/781)

Set the not-found page HTTP header to 404

---

apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/layout.tsx
apps/pdc-frontend/src/app/[locale]/(rootLayout)/layout.tsx
apps/vth-frontend/src/app/[locale]/(nestedNavLayout)/layout.tsx
apps/vth-frontend/src/app/[locale]/(rootLayout)/layout.tsx

Follow-up PR for this [commit](https://github.com/frameless/strapi/commit/5d5f9c7e0fabb5a5d626679ba93f285c65a80376) due to a breaking change in the Footer component.

Fix the footer issue

---

packages/ui/src/components/Footer/index.module.scss
packages/ui/src/components/Footer/index.tsx

Before:
After:
Also, the `<li>` without an `<ul>` has been fixed.

fix: cleaner page footer link list rendering

---

apps/pdc-frontend/src/components/UtrechtSearchBar/index.tsx

De tekstinvoer heeft op dit moment geen toegankelijk label:
Deze PR fixt dat, zonder dat er extra vertalingen nodig zijn.

fix: gebruik "Zoeken" label van button ook voor textbox

---

.github/workflows/release.yml

Do not manage these variables via secrets, because then these values will be masked in all the GitHub Action logs.

ci: specify release commit author

---

.github/workflows/release.yml

> GitHub Packages only supports authentication using a personal access token (classic). For more information, see "Managing your personal access tokens."
source: [Working with the Container registry ➝ Authenticating to the Container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic)

ci: use GitHub classic token to publish Docker images

---

apps/pdc-frontend/src/app/[locale]/(openFormsLayout)/form/[...slug]/page.tsx
apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsEmbed.tsx
apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsScript.tsx
apps/pdc-frontend/src/util/openFormsValidation.ts

This fixes one of the last remaining accessibility issues detected by SiteImprove.
I refactored the OpenFormsEmbed component to support server side rendering of fallback content. I configured the Heading 1 with the form name as fallback content.

fix: show Heading 1 with form name while loading form

---

README.md
apps/strapi.frameless.io/docs/developers/readme.md

While starting the Strapi pdc environment for the first time I ran into some issues.

docs: improve readme to include all env variables and docker-compose

---

.changeset/spotty-ravens-end.md
apps/pdc-dashboard/config/sync/admin-role.beheerder-m5uxzjc8.json
apps/pdc-dashboard/config/sync/admin-role.kennisbank-lezer-m5uvxm3k.json
apps/pdc-dashboard/config/sync/admin-role.kennisbank-schrijver-m5uxgzkp.json
apps/pdc-dashboard/config/sync/admin-role.pdc-lezer-m5uuxokf.json
apps/pdc-dashboard/config/sync/admin-role.pdc-schrijver-m5uxb98h.json

**Note**: There is a small issue when using only the PDC Lezer or Schrijver roles. The issue involves receiving an error message like the one below. 
This happens because of the internal field:
- The field has a two-way relationship with the product.
- The internal field is located in the dynamic-zone/sections, which means we cannot assign it to a role.
**The solution is**:
- PDC Lezer: Has view access to the internal field.
- PDC Schrijver: Can only view the internal field.
[Issue-991](https://github.com/frameless/strapi/issues/991) 
[issue-979](https://github.com/frameless/strapi/issues/979)

feat: add roles for pdc-dashboard

---

.changeset/healthy-pens-stare.md
apps/overige-objecten-api/src/utils/createHTMLFiles.tsx
apps/overige-objecten-api/src/utils/generateKennisartikelObject.ts
apps/overige-objecten-api/src/utils/index.ts
apps/overige-objecten-api/src/utils/renderMarkdownToString.tsx

[issue](https://github.com/frameless/strapi/issues/981)

fix: integrate price field into internal collection

---

apps/strapi.frameless.io/docs/handboek/rollen-en-mogelijkheden-in-strapi-dashboard.md

docs: add the roles and permissions documentation

---

apps/pdc-dashboard/src/components/components/additional-information.json

Renamed `components_components_additional_informations` to a shorter name to avoid database errors caused by exceeding identifier length limits. Fixes issues related to Strapi's database schema constraints.
https://github.com/strapi/strapi/issues/12101

fix(pdc-dashboard): shorten component name to prevent database identifier length issues 

---

.eslintrc.js
packages/utils/global.d.ts
packages/utils/jest.config.ts
packages/utils/package.json
packages/utils/rollup.config.ts
packages/utils/src/errorHandler/index.test.ts
packages/utils/src/errorHandler/index.ts
packages/utils/src/fetchData/index.test.ts
packages/utils/src/fetchData/index.ts
packages/utils/src/get-strapi-plugin-name/index.test.ts
packages/utils/src/get-strapi-plugin-name/index.ts
packages/utils/src/index.ts
packages/utils/tsconfig.json
packages/utils/tsconfig.test.json
yarn.lock

[Issue](https://github.com/frameless/strapi/issues/906)

Create utils package

---

.changeset/rotten-eagles-hope.md
apps/overige-objecten-api/src/__mocks__/getStrapiVacData.ts
apps/overige-objecten-api/src/controllers/objects/create.ts
apps/overige-objecten-api/src/controllers/objects/update.ts
apps/overige-objecten-api/src/queries/index.ts
apps/overige-objecten-api/src/strapi-product-type.ts
apps/overige-objecten-api/src/utils/getVacData.ts
apps/pdc-dashboard/config/sync/admin-role.beheerder-m5uxzjc8.json
apps/pdc-dashboard/config/sync/admin-role.kennisbank-lezer-m5uvxm3k.json
apps/pdc-dashboard/config/sync/admin-role.kennisbank-schrijver-m5uxgzkp.json
apps/pdc-dashboard/config/sync/admin-role.strapi-super-admin.json
apps/pdc-dashboard/config/sync/core-store.plugin_content_manager_configuration_components##components.vac.json
apps/pdc-dashboard/src/components/components/vac.json
apps/strapi-admin-extensions/src/docs/openapi.yaml
apps/strapi-admin-extensions/src/queries/index.ts

[issue](https://github.com/frameless/strapi/issues/1067)

Update vac trefwoorden to text field

---

packages/preview-button/admin/src/components/PreviewLink/index.css

fix(preview-button): update dialog backdrop color `rgb(0 0 0 / 30%)`

---

.changeset/lazy-phones-reply.md
apps/pdc-frontend/src/util/buildURL.ts

if isOrigin is false, getURL returns a URL object instead of a string.

fix: fix buildURL function

---

.changeset/tidy-boats-cry.md
apps/pdc-frontend/package.json
apps/pdc-frontend/src/components/OpenFormsEmbed/OpenFormsEmbed.tsx
yarn.lock

There are two issues:
- When importing the component via `@utrecht/open-forms-container-react/dist/css`, the CSS doesn't work. We still need to import the CSS manually from `@utrecht/open-forms-container-css/dist/index.css`.
- When trying to import the component from `@utrecht/open-forms-container-react` directly (without using /dist), there's a TypeScript issue related to missing or incorrect types.

feat(pdc-frontend): integrated `<OpenFormsContainer/>` into pdc-frontend

---

apps/pdc-frontend/src/query/index.ts

We disabled the flo-legal query because it is no longer available after being disabled in Strapi.

fix(pdc-frontend): disable flo-legal from graphql
